---
title: "Practica Final Parte 1"
author: "Xavier Vives, Josep Damià Ruiz, Antonio Marin y Martí Paredes"
output:
  pdf_document: default
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
  word_document: default
  html_document:
    df_print: paged
---

\tableofcontents 
\newpage

## **1. Cargad en un dataframe los datos del fichero listings.csv y construid un nuevo data frame**

```{r 1}
datos_raw = read.csv("listings.csv")
datos = datos_raw[-c(1,2,3,5,14,15)]
```

## **2. Renombrar las variables al castellano.**

```{r 2}
names(datos)[names(datos) == "host_name"] <- "Nombre_propietario"
names(datos)[names(datos) == "neighbourhood"] <- "Vecindario"
names(datos)[names(datos) == "latitude"] <- "Lat."
names(datos)[names(datos) == "longitude"] <- "Long."
names(datos)[names(datos) == "room_type"] <- "Tipo_habitación"
names(datos)[names(datos) == "price"] <- "Precio"
names(datos)[names(datos) == "minimum_nights"] <- "Min.noches"
names(datos)[names(datos) == "number_of_reviews"] <- "N_reseñas"
names(datos)[names(datos) == "number_of_reviews_ltm"] <- "Res.mes"
names(datos)[names(datos) == "availability_365"] <- "Disponibilidad_año"

names(datos)
```

## **3. Calcular mínimo, máximo, media, varianza, cuartiles y mediana.**

```{r 3}
minimo = unname(sapply(datos[c(3,4,6,7,8,9)],FUN=min))
maximo = unname(sapply(datos[c(3,4,6,7,8,9)],FUN=max))
media = unname(sapply(datos[c(3,4,6,7,8,9)],FUN=mean))
varianza = unname(sapply(datos[c(3,4,6,7,8,9)],FUN=var))
cuartiles = sapply(datos[c(3,4,6,7,8,9)],FUN=quantile)

rownames(cuartiles)<-(c("Cuartil_0","Cuartil_1","Mediana","Cuartil_3","Cuartil_4"))

datosEstadisticos=0

datosEstadisticos=minimo
datosEstadisticos<-rbind(datosEstadisticos, maximo)
datosEstadisticos<-rbind(datosEstadisticos, media)
datosEstadisticos<-rbind(datosEstadisticos, varianza)
datosEstadisticos<-rbind(datosEstadisticos,cuartiles)

datosEstadisticos
```

## **4. Tablas de frecuencias absolutas.**

```{r 4}
table(datos$Vecindario)
table(datos$Nombre_propietario)
table(datos$Tipo_habitación)
```